name    'echoes-postgrexc'
version '0.1.0'
source 'UNKNOWN'
author 'ECHOES Technologies <contact@echoes-tech.com>'
license 'Apache License, Version 2.0'
summary 'Postgres-XC Module'
description 'Configure a cluster with 2 database, 1 GTM and 1 GTM standby. Also add some bash script for high availability'
project_page 'https://github.com/echoes-tech/puppet-postgres_xc'
dependency 'puppetlabs/stdlib', '>= 0.1.6'
