name    'echoes-postgrexc'
version '0.1.0'
source 'UNKNOWN'
author 'echoes'
license 'Apache License, Version 2.0'
summary 'Configure a database cluster with Postgre-XC'
description 'Configure a cluster with 2 database, 1 GTM and 1 GTM standby. Also add some bash script for high availability'
project_page 'UNKNOWN'
